package io.github.aaronjang.opendart.internal

val REPORT_KEYWORD_MAP: Map<String, String> = mapOf(
    "조건부자본증권미상환" to "cndlCaplScritsNrdmpBlce",
    "미등기임원보수" to "unrstExctvMendngSttus",
    "회사채미상환" to "cprndNrdmpBlce",
    "단기사채미상환" to "srtpdPsndbtNrdmpBlce",
    "기업어음미상환" to "entrprsBilScritsNrdmpBlce",
    "채무증권발행" to "detScritsIsuAcmslt",
    "사모자금사용" to "prvsrpCptalUseDtls",
    "공모자금사용" to "pssrpCptalUseDtls",
    "임원전체보수승인" to "drctrAdtAllMendngSttusGmtsckConfmAmount",
    "임원전체보수유형" to "drctrAdtAllMendngSttusMendngPymntamtTyCl",
    "주식총수" to "stockTotqySttus",
    "회계감사" to "accnutAdtorNmNdAdtOpinion",
    "감사용역" to "adtServcCnclsSttus",
    "회계감사용역계약" to "accnutAdtorNonAdtServcCnclsSttus",
    "사외이사" to "outcmpnyDrctrNdChangeSttus",
    "신종자본증권미상환" to "newCaplScritsNrdmpBlce",
    "증자" to "irdsSttus",
    "배당" to "alotMatter",
    "자기주식" to "tesstkAcqsDspsSttus",
    "최대주주" to "hyslrSttus",
    "최대주주변동" to "hyslrChgSttus",
    "소액주주" to "mrhlSttus",
    "임원" to "exctvSttus",
    "직원" to "empSttus",
    "임원개인보수" to "hmvAuditIndvdlBySttus",
    "임원전체보수" to "hmvAuditAllSttus",
    "개인별보수" to "indvdlByPay",
    "타법인출자" to "otrCprInvstmntSttus",
)

val EVENT_KEYWORD_MAP: Map<String, String> = mapOf(
    "부도발생" to "dfOcr",
    "영업정지" to "bsnSp",
    "회생절차" to "ctrcvsBgrq",
    "해산사유" to "dsRsOcr",
    "유상증자" to "piicDecsn",
    "무상증자" to "fricDecsn",
    "유무상증자" to "pifricDecsn",
    "감자" to "crDecsn",
    "관리절차개시" to "bnkMngtPcbg",
    "소송" to "lwstLg",
    "해외상장결정" to "ovLstDecsn",
    "해외상장폐지결정" to "ovDlstDecsn",
    "해외상장" to "ovLst",
    "해외상장폐지" to "ovDlst",
    "전환사채발행" to "cvbdIsDecsn",
    "신주인수권부사채발행" to "bdwtIsDecsn",
    "교환사채발행" to "exbdIsDecsn",
    "관리절차중단" to "bnkMngtPcsp",
    "조건부자본증권발행" to "wdCocobdIsDecsn",
    "자산양수도" to "astInhtrfEtcPtbkOpt",
    "타법인증권양도" to "otcprStkInvscrTrfDecsn",
    "유형자산양도" to "tgastTrfDecsn",
    "유형자산양수" to "tgastInhDecsn",
    "타법인증권양수" to "otcprStkInvscrInhDecsn",
    "영업양도" to "bsnTrfDecsn",
    "영업양수" to "bsnInhDecsn",
    "자기주식취득신탁계약해지" to "tsstkAqTrctrCcDecsn",
    "자기주식취득신탁계약체결" to "tsstkAqTrctrCnsDecsn",
    "자기주식처분" to "tsstkDpDecsn",
    "자기주식취득" to "tsstkAqDecsn",
    "주식교환" to "stkExtrDecsn",
    "회사분할합병" to "cmpDvmgDecsn",
    "회사분할" to "cmpDvDecsn",
    "회사합병" to "cmpMgDecsn",
    "사채권양수" to "stkrtbdInhDecsn",
    "사채권양도결정" to "stkrtbdTrfDecsn",
)

val REGSTATE_KEYWORD_MAP: Map<String, String> = mapOf(
    "주식의포괄적교환이전" to "extrRs",
    "합병" to "mgRs",
    "증권예탁증권" to "stkdpRs",
    "채무증권" to "bdRs",
    "지분증권" to "estkRs",
    "분할" to "dvRs",
)
